# Model arguments
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger_lm: true
use_liger_kernel: true

# Data training arguments
dataset_name: Skywork/Skywork-Reward-Preference-80K-v0.2
dataset_split: train
preprocessing_num_workers: 8
auto_insert_empty_system_msg: true

# Method
use_batch_sum: true
bsr_lambda: 1.0e-3

# SFT trainer config
bf16: true
do_eval: false
tf32: true
torch_compile: false
optim: paged_adamw_8bit
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: ### NOTE: HF repo id
learning_rate: 2.0e-6
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: linear
max_length: 2048
max_steps: -1
num_train_epochs: 1
output_dir: ### NOTE: Output directory for the model checkpoint
overwrite_output_dir: true
per_device_train_batch_size: 16
remove_unused_columns: true
report_to:
- wandb
save_strategy: "epoch"
seed: 90
warmup_ratio: 0.05

# Hub
push_to_hub: true
hub_private_repo: true
